### ISSUE TITLE
Message from debugger: Terminated due to signal 9

### ISSUE THREAD

**Issue by Omfe** [Vizbii/morphii-sdk-ios#1]
Hi Im using the Authentication service just like the example you put in for Objective-C but Im getting a crash apparently due to a memory leak? I am trying to figure out whats happening or the reasons, but I get this message from the console after I hit continue to the crash:
"Message from debugger: Terminated due to signal 9"
This is as soon as I use the "authenticateWithUserame" method.

Thank you!

**Comment by wrightmg** [comment]
Thank you for your message. Please try using release 0.65 of the SDK. We also added sample Objective-C code to the repo.
